apiVersion: v1
kind: ConfigMap
metadata:
  name: mongoclient-cm
  labels:
    app: {{ include "mongoclient.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "mongo-endpoint": "{{ .Values.config.mongoEndpoint }}",
      "mongo-port": "{{ .Values.config.mongoPort }}",
      "client-port": "{{ .Values.config.clientPort }}"
    }


